#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100 fizzbuzz style
i=1
for i in {1..100}
do
	if ! (($i % 3))
	then
		if ! (($i % 5))
		then
			echo "FizzBuzz"
		else
			echo "Fizz"
		fi
	elif ! (($i % 5))
	then
		if (($i % 3))
		then
			echo "Buzz"
		fi
	else
		echo "$i"
	fi
done
