#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
i=1
while [ $i -le 10 ]
do
	printf "%s\n" "Best School"
	if [ $i -eq 9 ]
	then
		printf "%s\n" "Hi"
	fi
	((i++))
done
