#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and: 'good luck' on 4, 'bad luck' on 8, 'Best School' on others.
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		printf "%s\n" "bad luck"
	elif [ $i -eq 8 ]
	then
		printf "%s\n" "good luck"
	else
		printf "%s\n" "Best School"
	fi
	((i++))
done
