#!/usr/bin/env bash
#Display 1-20 with 4 bad luck from china, 9 back luck from japan, and 17 bad luck from italy
i=1
while [ $i -le 20 ]
do
	printf "%s\n" "$i"
	if [ $i -eq 4 ]
	then
		printf "%s\n" "bad luck from China"
	elif [ $i -eq 9 ]
	then
		printf "%s\n" "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		printf "%s\n" "bad luck from Italy"
	else
	fi
	((i++))
done
