#!/usr/bin/env bash
#Display 1-20 with 4 bad luck from china, 9 back luck from japan, and 17 bad luck from italy
i=1
while [ $i -le 20 ]
do
	printf "%s\n" "$i"
	case "$i" in
		#case 1
		4) printf "%s\n" "bad luck from China" ;;

		#case 2
		9) printf "%s\n" "bad luck from Japan" ;;

		#case 3
		17) printf "%s\n" "bad luck from Italy" ;;
	esac
	((i++))
done
