#!/usr/bin/env bash
#display time for 12 hours and 59 minutes
minute=1
hour=0
while [ $hour -le 12 ]
do
	printf "%s\n" "Hour: $hour"
	while [ $minute -le 59 ]
	do
		printf "%s\n" "$minute"
		((minute++))
	done
	((minute = 1))
	((hour++))
done
